In [32]:
import scipy.stats as st
import numpy as np 

# Exmple-1


In [33]:
df = 6-1
df

5

In [34]:
Chi_table = 11.07

In [37]:
Oi=np.array([22,17,20,26,22,13])
Ei=np.array([20,20,20,20,20,20])

In [38]:
Chi_cal=np.sum(np.square(Oi-Ei)/Ei)

In [39]:
if Chi_cal > Chi_table:                      
    print("Ha is Right")                
else :                                    
    print("Ho is Right") 

Ho is Right


# Exmple-2

In [55]:
row1 = np.array([40,45,25,10])
row2 = np.array([35,30,20,30])

In [77]:
n=235
Chi_table1= 7.815

In [78]:
sum_r1 = np.sum(row1)
sum_r2 = np.sum(row2)
sum_r1 , sum_r2

(120, 115)

In [79]:
sum_row = np.array([sum_r1 , sum_r2])
sum_row

array([120, 115])

In [80]:
sum_cal = row1+row2
sum_cal

array([75, 75, 45, 40])

In [81]:
Ei = []
for i in sum_row:
    for j in sum_cal:
        value = (i*j)/n
        Ei.append(value)
Ei

[38.297872340425535,
 38.297872340425535,
 22.97872340425532,
 20.425531914893618,
 36.702127659574465,
 36.702127659574465,
 22.02127659574468,
 19.574468085106382]

In [82]:
Oi = np.array([40,45,25,10,35,30,20,30])
Oi

array([40, 45, 25, 10, 35, 30, 20, 30])

In [83]:
Chi_cal1=np.sum(np.square(Oi-Ei)/Ei)
Chi_cal1

13.788747987117553

In [84]:
if Chi_cal > Chi_table1:                      
    print("Ha is Right")                
else :                                    
    print("Ho is Right") 

Ha is Right
